name: open3d
channels:
  - defaults
dependencies:
  - astroid=2.4.2
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.1
  - backports.tempfile=1.0
  - backports.weakref=1.0.post1
  - beautifulsoup4=4.9.3
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2020.10.14
  - certifi=2020.6.20
  - cffi=1.14.0
  - chardet=3.0.4
  - click=7.1.2
  - conda=4.9.1
  - conda-build=3.20.5
  - conda-package-handling=1.6.1
  - conda-verify=3.4.2
  - cryptography=2.9.2
  - cycler=0.10.0
  - decorator=4.4.2
  - expat=2.2.10
  - filelock=3.0.12
  - freetype=2.10.4
  - future=0.18.2
  - glob2=0.7
  - icu=58.2
  - idna=2.9
  - intel-openmp=2020.2
  - ipython=7.18.1
  - ipython_genutils=0.2.0
  - isort=5.6.4
  - jedi=0.17.2
  - jinja2=2.11.2
  - jpeg=9b
  - kiwisolver=1.3.0
  - lazy-object-proxy=1.4.3
  - lcms2=2.11
  - libarchive=3.4.2
  - liblief=0.10.1
  - libpng=1.6.37
  - libtiff=4.1.0
  - libxml2=2.9.10
  - lz4-c=1.9.2
  - markupsafe=1.1.1
  - matplotlib=3.3.2
  - matplotlib-base=3.3.2
  - mccabe=0.6.1
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.2.0
  - mkl_random=1.1.1
  - numpy=1.19.2
  - numpy-base=1.19.2
  - olefile=0.46
  - openssl=1.1.1h
  - parso=0.7.0
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.0.1
  - pip=20.0.2
  - pkginfo=1.6.0
  - prompt-toolkit=3.0.8
  - psutil=5.7.2
  - py-lief=0.10.1
  - pycosat=0.6.3
  - pycparser=2.20
  - pygments=2.7.2
  - pylint=2.6.0
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pysocks=1.7.1
  - python=3.8.3
  - python-dateutil=2.8.1
  - python-libarchive-c=2.9
  - pytz=2020.1
  - pyyaml=5.3.1
  - qt=5.9.7
  - requests=2.23.0
  - ripgrep=12.1.1
  - ruamel_yaml=0.15.87
  - setuptools=46.4.0
  - sip=4.19.13
  - six=1.14.0
  - soupsieve=2.0.1
  - sqlite=3.31.1
  - tk=8.6.8
  - toml=0.10.1
  - tornado=6.0.4
  - tqdm=4.46.0
  - traitlets=5.0.5
  - urllib3=1.25.8
  - wcwidth=0.2.5
  - wheel=0.34.2
  - wrapt=1.11.2
  - xz=5.2.5
  - yaml=0.1.7
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - argon2-cffi==20.1.0
    - async-generator==1.10
    - attrs==20.2.0
    - bleach==3.2.1
    - defusedxml==0.6.0
    - entrypoints==0.3
    - ipykernel==5.3.4
    - ipywidgets==7.5.1
    - jsonschema==3.2.0
    - jupyter-client==6.1.7
    - jupyter-core==4.6.3
    - jupyterlab-pygments==0.1.2
    - mistune==0.8.4
    - nbclient==0.5.1
    - nbconvert==6.0.7
    - nbformat==5.0.8
    - nest-asyncio==1.4.2
    - notebook==6.1.4
    - packaging==20.4
    - pandocfilters==1.4.3
    - prometheus-client==0.8.0
    - pyrsistent==0.17.3
    - pyzmq==19.0.2
    - send2trash==1.5.0
    - terminado==0.9.1
    - testpath==0.4.4
    - webencodings==0.5.1
    - widgetsnbextension==3.5.1
